### ISSUE TITLE
https://registry.npmjs.org/@algomart%2fschemas - Not found

### ISSUE THREAD

**Issue by djmbdv** [deptagency/algomart#100]
Package not found

**Comment by jakerainis** [comment]
@djmbdv this isn't a public package. It gets built within the project and is aliased throughout the application. If you're getting an error when running `npm install`, can you confirm you're running Node >= v16 as well as NPM 7?

**Comment by djmbdv** [comment]
this happens when I run docker-compose up .

**Comment by jakerainis** [comment]
Ah gotcha. There might be some bugs in the docker-compose that we'll have to look into. Coincidentally, running the monorepo without Docker is faster at the moment, and might be easier for you to set up that way. Sorry for the trouble.

**Comment by jakerainis** [comment]
@djmbdv I suspected that the Node version was out of date, but was able to get through the install step. Would you be able to provide any relevant system specs (OS, Docker version, etc) that we might be able to use to attempt reproducing the issue with?
