### ISSUE TITLE
Can create NFT template without unique code, but can't edit code

### ISSUE THREAD

**Issue by brandonaaskov** [deptagency/algomart#13]
## Overview

An NFT template can be created in the CMS without a unique code, but that blank unique code cannot be changed without deleting or archiving the entry.

**Comment by smonn** [comment]
This is an odd one. It could be that the CMS database migrations weren't been applied correctly. The underlying DB column is supposed to be unique and not nullable. It wasn't in nfty-mart but it was in my local DB. Created a PR to ensure it's correctly setup going forward and manually updated the DB in question here.

Also, when NFT templates (also applies for pack templates) are marked as published, most fields cannot be edited as they are used when we generate the _immutable_ assets on Algorand.
