### ISSUE TITLE
Infinite Loop on Sign-in

### ISSUE THREAD

**Issue by brandonaaskov** [deptagency/algomart#15]
## Overview

As an aside, it drives me nuts it says "sign in" if you intend to sign up.

That said, the flow is broken right now (at least on nfty-mart): https://share.brandonontheinternet.com/Kou7ZryJ

I just infinitely loop on the same sign in flow.

**Comment by brandonaaskov** [comment]
Forgot to post the error, had the wrong debug tool open: 
![image](https://user-images.githubusercontent.com/445778/139779195-d7e626f8-24f5-479a-a3ff-c42584e97c8e.png)

**Comment by brandonaaskov** [comment]
Just logged into Safari just fine so I should point out that was in Brave ☝️

**Comment by smonn** [comment]
This seems isolated to Brave, I'll close this issue. It works in Brave after turning off the shields:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/44818/139864345-bb75981a-8ce4-48e5-99e7-9ede90cabf0a.png">

My guess is it prevents the required cookie(s) from being set during login. Not sure there's much we can do about that short of not using Firebase.
