### ISSUE TITLE
SPIKE: smart contract to ensure peer-to-peer transaction in marketplace

### ISSUE THREAD

**Issue by smonn** [deptagency/algomart#208]
## Spike findings

We will remove the default frozen setting from any new assets, but keep clawback address until the initial payment for the NFT has cleared (after seven days). This way, we can still recover from credit card chargebacks. For non-credit card payments we might be able to do away with the clawback right away instead of having a 7+ day "lock" period.

The smart contract will be a fairly standard auction with escrow:

1. Seller selects NFT for sale and options (start date & end date, reserve price, min bid increment)
2. Smart contract auction gets deployed
3. Setup auction (send min funds, transfer NFT)
4. Bidders submit bids (if above reserve price and between start & end dates, approve)
5. Once end date is passed, close out auction (transfer NFT to winner, transfer funds to seller)

Other notes:

- Might have two smart contract options, one for ALGO payments and one for USDC. You would only be able to choose one at a time though.
- We might build in a royalty feature into the smart contracts for a listing fee, but this is still TBD.
- For existing NFTs that already have default frozen set, we will plan to add either a separate smart contract and/or an AlgoMart page which can unfreeze that NFT for a single account. Exact behavior of this is also TBD.

**Comment by brandonaaskov** [comment]
If we took payments in USDC, we'd have to support several wallets _or_ force people to only use certain versions of USDC. Because USDC works that way, it complicates matters for the end user. Acquiring USDC isn't any easier than acquiring Algos: IMO, we should just take Algos.

**Comment by brandonaaskov** [comment]
"We might build in a royalty feature into the smart contracts for a listing fee, but this is still TBD."

We'll definitely need the Algomart owner/operator to be able to define the resale royalty. The big reason the secondary marketplace is so desirable is because of that royalty that continues to earn on every resale.

**Comment by brandonaaskov** [comment]
I just read this in a requirement doc. Worth knowing.
"The smart contract should allow an option to put a hold of two weeks on NFT transfers when the receiving account is a custodial wallet (therefore paid with credit cards). During the holding period the NFT cannot be transferred outside the
wallet. (EU requirement)"
