### ISSUE TITLE
Releases & My Collection are buried on mobile.

### ISSUE THREAD

**Issue by afraser** [deptagency/algomart#26]
Not sure if this is an issue, but these links move from being extremely prominent on the top of the page on desktop to extremely subtle near the bottom on mobile.

<img width="376" alt="CleanShot 2021-11-02 at 16 02 14@2x" src="https://user-images.githubusercontent.com/1179515/139943962-e1e3926c-2a18-466f-8d38-22cc972475f2.png">

**Comment by jakerainis** [comment]
Just as an FYI, that's actually the footer you're referring to. The prominent links in the header are in the hamburger.

**Comment by afraser** [comment]
ok, but why is footer content on mobile at the top of the page in something called "mainNav" on desktop?

<img width="1046" alt="CleanShot 2021-11-03 at 05 21 08@2x" src="https://user-images.githubusercontent.com/1179515/140035501-b8c46015-097f-4f92-bed6-82012edcf64e.png">

**Comment by afraser** [comment]
ohhh sorry I see this is in addition to the menu, and also I didn't even notice that those links are down there on desktop as well. Kinda weird, but ok.
