### ISSUE TITLE
untransferredPacks appears to return the same pack multiple times

### ISSUE THREAD

**Issue by afraser** [deptagency/algomart#273]
## Overview

I see a notification after winning an auction that says "you have 6 unclaimed packs" when I only have 1 unclaimed pack with 6 collectibles in it. The problem appears to be in the packs service `untransferredPacks` method because it's joining in collectibles.

## To reproduce

1. Bid on and complete an auction for a pack with more than 1 collectible in it
2. Go through the flow to claim your pack
3. Notice the notification

**Comment by smonn** [comment]
Fixed in #335
