### ISSUE TITLE
Adhere to the ARC3 standard

### ISSUE THREAD

**Issue by jakerainis** [deptagency/algomart#4]
## Overview

Follow the [ARC3 standard](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0003.md) to improve compatibility with other (future) NFT storefronts. This will involve storing NFT data in IPFS and also generating a `metadata.json` file according to the ARC3 spec. 

## Features

- [x] #118 
- [x] #119 
- [x] #120

**Comment by brandonaaskov** [comment]
Found this in the Algorand ecosystem today:
https://arc3.xyz/
https://github.com/barnjamin/arc3.xyz

The design could use some work and the "Its hosted by Cloudflare but I cant get it to build there so I just committed my build directory" line in the README doesn't inspire confidence. But at least it's starting to be out there in the wild.
