### ISSUE TITLE
Admin user is not created when LOG_LEVEL isn't provided

### ISSUE THREAD

**Issue by dallashuggins** [deptagency/algomart#55]
## Overview

When `LOG_LEVEL` is not set, the admin user will not be created when the `npm run bootstrap` script is run. Therefore, it says it's successful in bootstrapping, but when you go to login with your username and password, it doesn't work.

## To reproduce

This should be for a new project _without_ a user.

1. Comment out `LOG_LEVEL`
2. Go to `apps/cms`
3. Run `npm run bootstrap`
4. Check CMS database table `directus_users`; there's no user. It also will specify in the logs it created the user if it worked. 

## Expected behavior

When `LOG_LEVEL` is `warn`, the admin user is created as expected and you can login.

## Additional context

When you console log `console.log({ userCount })` in the bootstrap file, it returns:
```
{
  usersCount: '17:00:32 ✨ Loaded extensions: price-conversion, pack-price\n0\n'
}
```

**Comment by IanPirro** [comment]
@dallashuggins did https://github.com/deptagency/algomart/pull/56 resolve this issue?

**Comment by dallashuggins** [comment]
@IanPirro It did - forgot I opened this. Closing since fixed. 🙌
