### ISSUE TITLE
Automate CMS setup that is currently manual

### ISSUE THREAD

**Issue by afraser** [deptagency/algomart#63]
## Overview

As a developer, I want to be able to get up and running via terminal commands only, so that I don't waste hours trying to figure out why the API can't talk to the CMS or why I don't see images in the app.

Image permissions step outlined [here](https://github.com/deptagency/algomart/tree/main/apps/cms#1-make-files-publicly-viewable) should be able to be replaced by a simple insert:

![image](https://user-images.githubusercontent.com/1179515/141326858-e2a787b3-f30c-48d5-a0b4-acc04f53e1c2.png)

The user token step outlined [here](https://github.com/deptagency/algomart/tree/main/apps/cms#2-add-token-for-user) should be replaceable by updating the user record token column:

<img width="2103" alt="CleanShot 2021-11-11 at 10 48 23@2x" src="https://user-images.githubusercontent.com/1179515/141327409-f0666d3b-a882-4d84-ab57-dcf2ba61aca7.png">

I propose we update the cms seed script to do both of these things.

**Comment by kevlarr** [comment]
Do we want a solution that works for deploys, too? We don't run the seed script on deploys since it isn't repeatable without truncating tables.

**Comment by smonn** [comment]
Should be able to do this via the Directus API, similarly to how we use it in the seed script. @kevlarr are we running the CMS bootstrap step? Meaning, `npm run bootstrap` during deploys?

**Comment by kevlarr** [comment]
@smonn Yeah, it runs every time a container starts up https://github.com/deptagency/algomart/blob/main/docker/deploy/cms/run.sh#L4

**Comment by kevlarr** [comment]
This is also mentioned in the docs in several places for [local dev](https://github.com/deptagency/algomart#adding-the-cms-key-to-the-admin-user) and [the deploy docs](https://github.com/deptagency/algomart/tree/main/docs/deploy/06-post-deploy-steps#1-add-token-to-admin-user) so the docs should be updated accordingly, in both places if fixed for local + deploy, or just in the main readme if only in the seed script

**Comment by kevlarr** [comment]
Even if we do fix it, I think we should still call it out in the docs as prominently as possible. Users need to be aware that the admin user's access token is a thing, just so no one gets into the very easy to get into situation where that initial admin user is updated or removed and the API can no longer authenticate.

**Comment by afraser** [comment]
Making the seed script repeatable is another thing I'd love to see done... if it's not a big task I'd say it should be rolled into this one. That's yet another thing that's bitten me.
