### ISSUE TITLE
SPIKE: 3DS

### ISSUE THREAD

**Issue by dallashuggins** [deptagency/algomart#72]
## Overview

Since we need to support 3DS verification, this is a for doing research and testing so we can know exactly what needs to happen for implementation.  

## Additional context

_Questions to look into_
- Is Circle's 3DS support only in the Sandbox environment?
- We need a success/error page for the user to return to upon successful verification or an error. What is needed for this?
- How would the payment flow change?
- Can we programmatically determine what countries require 3DS?
- What countries require 3DS?

**Comment by smonn** [comment]
Still waiting to confirm if this is available in non-sandbox, but it seems we can implement this like the following:

1. Initiate payment as we do today, but set verification to `three_d_secure` (and the success/failure URLs accordingly).
2. Wait for status for the payment. If the status appears like the below example, then redirect from the checkout page to the 3D Secure page. Upon return, proceed with status checks and then continue with regular flow.

```js
{
  data: {
    id: '<Redacted UUID>',
    type: 'payment',
    merchantId: '<Redacted UUID>',
    merchantWalletId: '<Redacted ID>',
    source: { id: '<Redacted UUID>', type: 'card' },
    description: 'Payment Test',
    amount: { amount: '5.66', currency: 'USD' },
    status: 'action_required',
    requiredAction: {
      type: 'three_d_secure_required',
      redirectUrl: 'https://web-sandbox.circle.com/v1/3ds/session/<Redacted UUID>'
    },
    refunds: [],
    createDate: '2021-11-30T18:07:28.852Z',
    updateDate: '2021-11-30T18:07:29.301067Z',
    metadata: { email: '<Redacted Email Address>' }
  }
}
```

If we encounter a failure in the 3D Secure flow (meaning we end up on the failure URL), then display a similar payment error message as we do today.

All of this also, probably, means we don't have to worry about which country the payment is originating from, Circle will direct us into the right flow as needed. Still waiting for confirmation on this part too.
