### ISSUE TITLE
Scheduled task for checking wire payments

### ISSUE THREAD

**Issue by dallashuggins** [deptagency/algomart#76]
## Overview

Create task for checking the Circle payments endpoint for successful wire transfer. 

We cannot transfer the asset automatically without the passcode, so this may be for sending them an email to let them know payment was verified, and then they can login to make the transfer. We'll need a form for gathering the passcode and initiating the transfer, since payment will be complete.

## Additional context

We currently have a task for retrieving pending payments and looking up the payment status and updating it in the database. There will not be a payment created initially, so this cannot be used for checking for wire transfers.

The [get payments endpoint](https://developers.circle.com/reference#payments-payments-get) has a query param for filtering by wire transfers (`type` = `wire`). The `source.id` attribute matches the ID of the bank account initially created. The status will be `paid` when the funds have settled.

This could be a manual step though, so this isn't necessary but a nice-to-have. But we'll need to mark the user as the owner of the pack once we get confirmation of payment.

Should there be a time limit to how long the user has to initiate wire transfer? AKA should we support bid expiration for these auctions. If we do, we should probably double check the status of payment right before assigning to next bidder, and maybe add time if the status is pending. 

We need to check the price of the successful payment as well during this process.

**Comment by CarterRose** [comment]
Hey text me if you need code for transfer

**Comment by dallashuggins** [comment]
Closing since the ability to find a wire payment using the scheduled task was completed in #75 and the ticket #138 is for handling the paid status, though we may just not allow transfer out but award the pack right away, and set an expiration date for monitoring for payment.
